[project]
name = "pharmacy-dwh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "blenlkj", email = "sblenlkj@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "psycopg2-binary>=2.9.9",
    "PyYAML>=6.0",
]

[project.scripts]
pharmacy-dwh = "pharmacy_dwh:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
